export default {
    createNewExperience: 'Alt+N',
    openExperience: 'Alt+O',
    saveExperience: 'Alt+S',
    saveExperienceAs: 'Alt+Shift+S',
    import3DModel: 'Ctrl+I',
    duplicateActiveElement: '<',
    copyActiveElement: 'Ctrl+C',
    pasteElement: 'Ctrl+V',
    toggleToolsPanel: 'Ctrl+Alt+T',
    toggleElementsLibrary: 'Ctrl+Alt+L',
    toggleOutliner: 'Ctrl+Alt+O',
    toggleEditor: 'Ctrl+Alt+P',
    toggleBottomBar: 'Ctrl+Alt+B',
    toggleGrid: 'Ctrl+Alt+G',
    select: ' ',
    move: 'M',
    rotate: 'R',
    scale: 'Shift+R',
    playExperience: 'Alt+P',
}
